// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace RestApiAssignment4.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ProducerFeature : object, Xunit.IClassFixture<ProducerFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Producer.feature"
#line hidden
        
        public ProducerFeature(ProducerFeature.FixtureData fixtureData, RestApiAssignment4_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Producer", "This feature performs CRUD operations on Producer class", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Create a Producer")]
        [Xunit.TraitAttribute("FeatureTitle", "Producer")]
        [Xunit.TraitAttribute("Description", "Create a Producer")]
        [Xunit.InlineDataAttribute("{\"Name\":\"TestName\",\"Bio\":\"TestBio\",\"DOB\":\"2002-02-02\",\"Gender\":\"M\"}", "201", new string[0])]
        [Xunit.InlineDataAttribute("{\"Name\":\"\",\"Bio\":\"TestBio\",\"DOB\":\"2002-02-02\",\"Gender\":\"M\"}", "400", new string[0])]
        [Xunit.InlineDataAttribute("{\"Name\":\"TestName\",\"Bio\":\"\",\"DOB\":\"2002-02-02\",\"Gender\":\"M\"}", "400", new string[0])]
        [Xunit.InlineDataAttribute("{\"Name\":\"TestName\",\"Bio\":\"TestBio\",\"DOB\":\"\",\"Gender\":\"M\"}", "400", new string[0])]
        [Xunit.InlineDataAttribute("{\"Name\":\"TestName\",\"Bio\":\"TestBio\",\"DOB\":\"2002-02-02\",\"Gender\":\"\"}", "400", new string[0])]
        [Xunit.InlineDataAttribute("{\"Name\":\"TestName\",\"Bio\":\"TestBio\",\"DOB\":\"2025-01-01\",\"Gender\":\"M\"}", "400", new string[0])]
        [Xunit.InlineDataAttribute("{\"Name\":\"TestName\",\"Bio\":\"TestBio\",\"DOB\":\"2002-02-02\",\"Gender\":\"a\"}", "400", new string[0])]
        public void CreateAProducer(string request, string statusCode, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("request", request);
            argumentsOfScenario.Add("statusCode", statusCode);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a Producer", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
 testRunner.Given("I am a client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 7
 testRunner.When(string.Format("I am making a post request to \'/producers\' with the following Data \'{0}\'", request), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 8
 testRunner.Then(string.Format("response code must be {0}", statusCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Get All Producers")]
        [Xunit.TraitAttribute("FeatureTitle", "Producer")]
        [Xunit.TraitAttribute("Description", "Get All Producers")]
        public void GetAllProducers()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get All Producers", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 19
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 20
 testRunner.Given("I am a client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 21
 testRunner.When("I make GET Request to \'/producers\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 22
 testRunner.Then("response code must be 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 23
 testRunner.And("response data must look like \'[{\"id\":1,\"name\":\"TestName\",\"gender\":\"M\",\"dob\":\"2002" +
                        "-02-02T00:00:00\",\"bio\":\"TestBio\"}]\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Get a Producer by Id")]
        [Xunit.TraitAttribute("FeatureTitle", "Producer")]
        [Xunit.TraitAttribute("Description", "Get a Producer by Id")]
        [Xunit.InlineDataAttribute("/producers/1", "200", "{\"id\":1,\"name\":\"TestName\",\"gender\":\"M\",\"dob\":\"2002-02-02T00:00:00\",\"bio\":\"TestBio" +
            "\"}", new string[0])]
        [Xunit.InlineDataAttribute("/producers/100", "404", "Not found", new string[0])]
        public void GetAProducerById(string endpoint, string statusCode, string response, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("endpoint", endpoint);
            argumentsOfScenario.Add("statusCode", statusCode);
            argumentsOfScenario.Add("response", response);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get a Producer by Id", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 25
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 26
 testRunner.Given("I am a client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 27
 testRunner.When(string.Format("I make GET Request to \'{0}\'", endpoint), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 28
 testRunner.Then(string.Format("response code must be {0}", statusCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 29
 testRunner.And(string.Format("response data must look like \'{0}\'", response), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Update a Producer")]
        [Xunit.TraitAttribute("FeatureTitle", "Producer")]
        [Xunit.TraitAttribute("Description", "Update a Producer")]
        [Xunit.InlineDataAttribute("/producers/1", "{\"Name\":\"TestName\",\"Bio\":\"TestBio\",\"DOB\":\"2002-02-02\",\"Gender\":\"M\"}", "200", new string[0])]
        [Xunit.InlineDataAttribute("/producers/1", "{\"Name\":\"\",\"Bio\":\"TestBio\",\"DOB\":\"2002-02-02\",\"Gender\":\"M\"}", "400", new string[0])]
        [Xunit.InlineDataAttribute("/producers/1", "{\"Name\":\"TestName\",\"Bio\":\"\",\"DOB\":\"2002-02-02\",\"Gender\":\"M\"}", "400", new string[0])]
        [Xunit.InlineDataAttribute("/producers/1", "{\"Name\":\"TestName\",\"Bio\":\"TestBio\",\"DOB\":\"\",\"Gender\":\"M\"}", "400", new string[0])]
        [Xunit.InlineDataAttribute("/producers/1", "{\"Name\":\"TestName\",\"Bio\":\"TestBio\",\"DOB\":\"2002-02-02\",\"Gender\":\"\"}", "400", new string[0])]
        [Xunit.InlineDataAttribute("/producers/1", "{\"Name\":\"TestName\",\"Bio\":\"TestBio\",\"DOB\":\"2024-01-01\",\"Gender\":\"M\"}", "400", new string[0])]
        [Xunit.InlineDataAttribute("/producers/1", "{\"Name\":\"TestName\",\"Bio\":\"TestBio\",\"DOB\":\"2002-02-02\",\"Gender\":\"a\"}", "400", new string[0])]
        [Xunit.InlineDataAttribute("/producers/100", "{\"Name\":\"TestName\",\"Bio\":\"TestBio\",\"DOB\":\"2002-02-02\",\"Gender\":\"M\"}", "400", new string[0])]
        public void UpdateAProducer(string endpoint, string request, string statusCode, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("endpoint", endpoint);
            argumentsOfScenario.Add("request", request);
            argumentsOfScenario.Add("statusCode", statusCode);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update a Producer", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 35
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 36
 testRunner.Given("I am a client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 37
 testRunner.When(string.Format("I make PUT Request \'{0}\' with the following Data \'{1}\'", endpoint, request), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 38
 testRunner.Then(string.Format("response code must be {0}", statusCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Delete a Producer")]
        [Xunit.TraitAttribute("FeatureTitle", "Producer")]
        [Xunit.TraitAttribute("Description", "Delete a Producer")]
        [Xunit.InlineDataAttribute("/producers/1", "200", new string[0])]
        [Xunit.InlineDataAttribute("/producers/100", "404", new string[0])]
        public void DeleteAProducer(string endpoint, string statusCode, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("endpoint", endpoint);
            argumentsOfScenario.Add("statusCode", statusCode);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Delete a Producer", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 50
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 51
 testRunner.Given("I am a client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 52
 testRunner.When(string.Format("I make Delete Request \'{0}\'", endpoint), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 53
 testRunner.Then(string.Format("response code must be {0}", statusCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ProducerFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ProducerFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
